services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/src/src  # Mount source code vào đúng thư mục
      - /src/src/DoAn.Presentation.Api/bin  # Exclude bin
      - /src/src/DoAn.Presentation.Api/obj  # Exclude obj
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      TZ: "Asia/Ho_Chi_Minh"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=${DB_NAME_DEV};User Id=sa;Password=${DB_PASSWORD_DEV};TrustServerCertificate=True;"
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "${MINIO_ROOT_USER_DEV}"
      Minio__SecretKey: "${MINIO_ROOT_PASSWORD_DEV}"
      Minio__BucketName: "${MINIO_BUCKET_NAME_DEV}"
      Minio__WithSSL: "false"
      Minio__BaseUrl: "http://localhost/media"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # container_name: sqlserver-do-an-server-dev
    ports:
      - "${DB_PORT_DEV}:1433"
    environment:
      SA_PASSWORD: "${DB_PASSWORD_DEV}"
      ACCEPT_EULA: "Y"
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - sqlserver_data_dev:/var/opt/mssql

  minio:
    image: minio/minio
    # container_name: minio-do-an-server-dev
    ports:
      - "${MINIO_PORT_DEV}:9000"
      - "${MINIO_CONSOLE_PORT_DEV}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER_DEV}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD_DEV}
    volumes:
      - minio_data_dev:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:latest
    # container_name: nginx-do-an-server-dev
    ports:
      - "${NGINX_PORT_DEV}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  sqlserver_data_dev:
  minio_data_dev:
