FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src
ENV TZ=Asia/Ho_Chi_Minh

# Copy solution file
COPY *.sln .

# Copy all project files
COPY src/DoAn.Presentation.Api/*.csproj ./src/DoAn.Presentation.Api/
COPY src/DoAn.Core.Application/*.csproj ./src/DoAn.Core.Application/
COPY src/DoAn.Core.Domain/*.csproj ./src/DoAn.Core.Domain/
COPY src/DoAn.Infrastructure/*.csproj ./src/DoAn.Infrastructure/

# Restore dependencies
RUN dotnet restore

# Copy all source code
COPY src/ ./src/

EXPOSE 8080
WORKDIR /src/src/DoAn.Presentation.Api
CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080"]